### PR TITLE
use correct type for bladerf_get_frequency

### PR DESCRIPTION
**Pull request by larsks**
Building against ubuntu bionic (amd64) resulted in the following error:

```
    sdr_bladerf.c: In function 'show_config':
    sdr_bladerf.c:116:76: error: passing argument 3 of 'bladerf_get_frequency' from incompatible pointer type [-Werror=incompatible-pointer-types]
             (status = bladerf_get_frequency(BladeRF.device, BLADERF_MODULE_RX, &freq)) < 0 ||
                                                                                ^
    In file included from sdr_bladerf.c:23:0:
    /usr/include/libbladeRF.h:1117:15: note: expected 'bladerf_frequency * {aka long unsigned int *}' but argument is of type 'unsigned int *'
     int CALL_CONV bladerf_get_frequency(struct bladerf *dev,
^~~~~~~~~~~~~~~~~~~~~
```

This commit uses the correct type for the `freq` variable.

### CODE REVIEW

**Comment by mutability** [comment]
This is, unfortunately, an incompatible change in the upstream headers and will break the build on e.g. jessie.

**Comment by larsks** [comment]
Good catch, thanks.

I've updated the pr to use `bladerf_frequency`. I'll take a look at the version conditional later.

**Comment by larsks** [comment]
Actually, the current version of the pr seems to build fine on debian jessie.

**Comment by mutability** [comment]
Breaks for me:

```sdr_bladerf.c: In function 'show_config':
sdr_bladerf.c:105:5: error: unknown type name 'bladerf_frequency'
     bladerf_frequency freq;
     ^
sdr_bladerf.c:116:76: error: pointer targets in passing argument 3 of 'bladerf_get_frequency' differ in signedness [-Werror=pointer-sign]
         (status = bladerf_get_frequency(BladeRF.device, BLADERF_MODULE_RX, &freq)) < 0 ||
                                                                            ^
In file included from sdr_bladerf.c:23:0:
/usr/include/libbladeRF.h:1261:15: note: expected 'unsigned int *' but argument is of type 'int *'
 int CALL_CONV bladerf_get_frequency(struct bladerf *dev,
               ^
cc1: all warnings being treated as errors
Makefile:41: recipe for target 'sdr_bladerf.o' failed
make[2]: *** [sdr_bladerf.o] Error 1
```

**Comment by mutability** [comment]
Not working in the current form, reopen if needed

**Comment by jprochazka** [comment]
You have this closed but  I was able to work out a fix. @larsks was close but there were a couple other minor changes needed in order to get things working. On top of changing `unsigned freq` to `bladerf_frequency freq` in sdr_bladerf.c a couple further change changes needed as well. 

You need to modify the LIBS variable in the file MakeFile by adding `-pthread` before `-lpthread`. This will fix the `dump1090.o: undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'` error I am guessing @mutability was running into in his last comment.

Being that building bladeRF from the master branch of their repository builds bladeRF2 you will need to modify Debian/control as well changing `libbladerf1 (>= 0.2016.06)` to `libbladerf2` in the dump1090-fa Depends line.

Tested and working on Unbuntu 19.04 Disco Dingo.
I have to step out now but If you wish I will submit a pull request reflecting these changes tonight.

**Comment by mutability** [comment]
A PR that fixes this without breaking builds for other versions would be
great if you can put that together.

**Comment by jprochazka** [comment]
Just need to test that changes to the Debian control file work with both libbladerf1 as well as libbladerf2. I have never done a | aka or for dependencies in a control file but from what I read it should work. I just want to make sure before submitting a pull request.

I just tried to upgrade my test machine from Ubuntu 16.04 to 19.04 and apparently the firmware does not play nice with the newer kernels. As soon as I am back up and running I will test the changes out and submit a pull request.

**Comment by mutability** [comment]
FWIW I just took a look at this on my bionic machine here and I can't reproduce the original build problem.

```libbladerf-dev:
  Installed: 0.2016.06-2
  Candidate: 0.2016.06-2
  Version table:
 *** 0.2016.06-2 500
        500 http://gb.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
```

I can entirely believe that there's an API change here but I don't see it with vanilla bionic.

**Comment by mutability** [comment]
I can't reproduce this against ubuntu disco amd64 either.
